pathParameters:
  cartId:
    name: cartId
    in: path
    description: The ID of the shopping cart.
    required: true
    schema:
      type: string
queryParameters:
  name:
    in: query
    name: name
    required: false
    description: Product name
    schema:
      type: string