type: object
properties:
  productId:
    type: string
    description: Product's unique ID
    example: a55657a2-7a90-4179-ac1a-b20b88af5dd8
  productName:
    type: string
    description: Product's name
    example: Wooden wardrobe
  soldQuantity:
    type: integer
    description: The sold quantity of product
  availableQuantity:
    type: integer
    description: The available quantity of product
  totalSaleAmount:
    type: number
    format: double
    description: Total sale amount
    example: 100
  isLowQuantity:
    type: boolean
